### ISSUE TITLE
Node Join

### ISSUE THREAD

**Issue by dirvine** [maidsafe/sn_routing#1806]
When a  node issues a `JoinRequest`  on the section we take the following steps

We check the chain for the node joining that has
`Left` but not `Relocated` then we would relocate this node  to another section as per #1805  We only relocate  `if section_size() > SAFE_SECTION_SIZE` otherwise we allow the node to simply rejoin here without penalty.

 then it will be given `Infant or Elder` status. The section votes on whether to accept this `node`  based on the following. 

if section_size() < Elder_size {
node == `Elder` // Valid network churn event

} else If  { section_size() < SAFE_SECTION_SIZE 
node == `Infant` // Valid network churn event (existing infants will age)

} else if { num_infants() < 2 {
  node == `infant` // not a network churn event
} else {
  // reply to node, to wait, we may accept him later
}

**Comment by madadam** [comment]
We went with different approach. Closing.
