### ISSUE TITLE
Revise the `simultaneous_joining_nodes` tests to verify they still do the right thing

### ISSUE THREAD

**Issue by madadam** [maidsafe/sn_routing#1935]
The tests might be relying on the old relocation behaviour and might not necessarily do what we want.

**Comment by jeanphilippeD** [comment]
See comment: https://github.com/maidsafe/routing/pull/1934#discussion_r353188132

**Comment by madadam** [comment]
All mock-network tests were removed in https://github.com/maidsafe/sn_routing/pull/2174 and is being replaced with a simpler and better test suite.
