### ISSUE TITLE
Changes to node ageing

### ISSUE THREAD

**Issue by madadam** [maidsafe/sn_routing#2078]
- Node age is a number between 4 and 255 (inclusive), so it's stored in `u8`.
- There is no `age_counter` anymore
- During network startup when there is only one section (the section with empty prefix) and the section size is less than `safe_section_size`, any churn event causes the ages of all the nodes in the section to increase by 1.
- After `safe_section_size`, the ageing logic changes as follow:
    - consider only churn events of mature nodes (adults or elders), ignore infants
    - calculate the BLS signature `sig` of the churn event
    - for each node, calculate `sig % 2^age`
    - if it is zero, increase age of that node by one and relocate it
    - otherwise do nothing

Notes:
- We will need to collect the BLS signatures of the churn events (`Online` and `Offline`) which we currently don't. The mechanism for that is already in place for `SectionInfo` events so this should not be hard
- We will need some way to perform 256-bit integer arithmetic. There is no built-in 256-bit integer type in rust, so we would need to find a crate or implement it ourselves (although the only operations we need is `2^u8` and `u256 % u256`, so it might not be too bad).

Edit: this task is actually a prerequisite for #2117 (parsec removal) because it removes the dependency of node-ageing/relocation on the order of churn events.

**Comment by dirvine** [comment]
We can take the first 2 bytes of the signature here. So a u16 will work as the numerator and save us working with large integer maths.

**Comment by madadam** [comment]
> We can take the first 2 bytes of the signature here. So a u16 will work as the numerator and save us working with large integer maths.

But `2^u8` is still potentially 256-bit number. Or do you want to use `wrapping_pow` or something like that?

**Comment by madadam** [comment]
Closed via https://github.com/maidsafe/sn_routing/pull/2185
