### ISSUE TITLE
Improve accumulation of message signatures with proofs of different lengths

### ISSUE THREAD

**Issue by madadam** [maidsafe/sn_routing#2108]
Most of the time the proofs of all the `MessageSignatures` for some given message will be the same, but when they are not we should be smarter in how we handle them. Currently we simply take the first proof we receive which means that a node can purposefully include proof that is too short in order to make the message untrusted (although it would have to somehow get its `MessageSignature` to the signature target first). We can try to take the longest proof instead which would improve the chances of the message being trusted by the destination, but could also be abused for low-impact malice - a node can purposefully include proof that is too long in order to increase the size of the resulting message. Maybe we should take the median-length proof?

**Comment by maqi** [comment]
no longer relevant
