### ISSUE TITLE
Require name change before promotion

### ISSUE THREAD

**Issue by madadam** [maidsafe/sn_routing#2112]
When a node is about to be promoted to elder, it needs to generate a new name for itself so that the elder sets are always unique. 

For example, currently we can have section progression like this:
1. `A, B, C, D`
2. `A, B, C, E`
3. `A, B, C, D`

So now 1 and 3 are identical which might make the section vulnerable to replay attacks (the demotion of `D` in step 2 could be replayed after step 3 to demote it again). There might be other, more subtle issues with this.

To prevent that, we should require that D changes its name before the promotion, so the progression would look like this (`D'` is the new name of `D`):
1. `A, B, C, D`
2. `A, B, C, E`
3. `A, B, C, D'`

The flow could look approximately like this:

1. The section decides to promote/demote some nodes (after a churn, ...)
2. The nodes that are not elders currently but that would become new elders are identified
3. A message is sent to these new to-be-elders (signed by the section and accumulated at the destination) to ask them to generate the new name
4. On receiving the message and verifying it, they generate the new name and send back a proof of that - a message containing the new name signed with the old key
5. When all proofs are received, the section proceeds with the promotion

To handle faulty nodes, we should give the to-be-elders a limited time to do the name change and if they fail to do so, we remove them from the promotion and replace with different nodes and repeat the process. 

Additional notes: The name change request message could additionally include a name interval into which the new name must fall which can then be used to keep the section balanced - so when a split happens, roughly half of the elders go into one subsection and half into the other. If this could be made reliable it could allow us to remove some of the complexity which we currently have to handle the case where all the elders end up in only one subsection.

**Comment by maqi** [comment]
moved to issue https://github.com/maidsafe/safe_network/issues/71
