### ISSUE TITLE
functions calling `send` in comm ignore the result of the `send`

### ISSUE THREAD

**Issue by Dylan-DPC** [maidsafe/sn_routing#2480]
The result of [Comm::send](https://github.com/maidsafe/sn_routing/blob/27a48a57dfa8202c54d298770f320eeb7fa5670b/src/routing/comm.rs#L156) is ignored when the function is called.  This should be change to reflect the logic of what's to be done if message hasn't been sent to the minimum delivery group size.

**Comment by maqi** [comment]
no longer relevant.
