### ISSUE TITLE
Hash should switch to multihash

### ISSUE THREAD

**Issue by dirvine** [maidsafe/sn_routing#918]
i.e. Have an identifier at start to allow hash upgrades, see https://github.com/jbenet/multihash

**Comment by afck** [comment]
What would be the benefit of this for the network? Which use of hashes would we upgrade?
(E.g. the data names? Would all the data in the network have to migrate then?)

**Comment by chpio** [comment]
hi, i made an alternative version of the multihash lib. i think it is more "rust idiomatic" than the original version. But it needs some work to be done, documentation and some api clean up.

https://github.com/chpio/mf-multihash.rs

**Comment by chpio** [comment]
> What would be the benefit of this for the network? Which use of hashes would we upgrade?
> (E.g. the data names? Would all the data in the network have to migrate then?)

Yes, you would need to upgrade all the hashes, but you get much easier updates for further changes to hashing with backward compatibility for old hashes.
